language: node_js
cache:
  directories:
    - node_modules # Cache Node Modules Folder
branches:
  only:
  - /.*/ # Run build on all branches
sudo: false
node_js:
- 'stable'
- '8'
install:
  - npm install
before_script:
  - npm run compile
script:
 - npm test
 - npm run lint